package gui;


import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.Theme;
import com.vaadin.annotations.Title;
import com.vaadin.annotations.VaadinServletConfiguration;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.event.FieldEvents;
import com.vaadin.server.VaadinRequest;
import com.vaadin.server.VaadinServlet;
import com.vaadin.ui.*;
import entity.lot.Lot;
import org.apache.log4j.Logger;
import service.LotService;
import service.LotServiceImpl;

import javax.servlet.annotation.WebServlet;

@Title("Auction")
@Theme("valo")
public class AddressbookUI extends UI {
    private static Logger log = Logger.getLogger(AddressbookUI.class);



    TextField filter = new TextField();
    @AutoGenerated
    private AbsoluteLayout mainLayout;
    @AutoGenerated
    private AbsoluteLayout absoluteLayout_18;
    @AutoGenerated
    private AbsoluteLayout absoluteLayout_4;
    @AutoGenerated
    private TextField textField_17;
    @AutoGenerated
    private TextField textField_16;
    @AutoGenerated
    private TextField textField_15;
    @AutoGenerated
    private TextField textField_14;
    @AutoGenerated
    private TextField textField_13;
    @AutoGenerated
    private TextField textField_12;
    @AutoGenerated
    private TextField textField_3;
    @AutoGenerated
    private TextField textField_4;
    @AutoGenerated
    private Button button_5 = new Button();
    @AutoGenerated
    private GridLayout gridLayout_2;
    @AutoGenerated
    private TextField textField_2;
    @AutoGenerated
    private GridLayout gridLayout_3;
    @AutoGenerated
    private AbsoluteLayout absoluteLayout_5;
    @AutoGenerated
    private Button button_1;
    @AutoGenerated
    private GridLayout gridLayout_5;
    @AutoGenerated
    private AbsoluteLayout absoluteLayout_3;
    @AutoGenerated
    private Button button_3 = new Button("new Lot");
    @AutoGenerated
    private Grid gridLayout_4;
    @AutoGenerated
    private AbsoluteLayout absoluteLayout_2;
    @AutoGenerated
    private NativeButton nativeButton_1;
    @AutoGenerated
    private TextField textField_18;
    @AutoGenerated
    private TextField textField_1;


    ContactForm contactForm = new ContactForm();

    LotService service = new LotServiceImpl();


    @Override
    protected void init(VaadinRequest request) {
        log.error("--------------------------in init");
        try {
            configureComponents();
        } catch (Exception e) {
            e.printStackTrace();
        }
        buildMainLayout();
        try {
            refreshContacts();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void configureComponents() throws Exception {
        log.error("in conf ++++++++++++++++++++++++++++++++++");
        button_3.addClickListener(new Button.ClickListener() {

            @Override
            public void buttonClick(Button.ClickEvent event) {
                contactForm.edit(new Lot());
            }
        });



    }


    @AutoGenerated
    private AbsoluteLayout buildMainLayout() {
        log.error("++++++++++++++++++++++++++++++++++=");
        // common part: create layout
        mainLayout = new AbsoluteLayout();
        mainLayout.setImmediate(false);
        mainLayout.setWidth("100%");
        mainLayout.setHeight("100%");

        // top-level component properties
        setWidth("100.0%");
        setHeight("100.0%");

        // absoluteLayout_2
        absoluteLayout_2 = buildAbsoluteLayout_2();
        mainLayout.addComponent(absoluteLayout_2,
                "top:20.0px;right:9.0px;left:40.0px;");

        // absoluteLayout_3
        absoluteLayout_3 = buildAbsoluteLayout_3();
        mainLayout.addComponent(absoluteLayout_3, "top:80.0px;left:40.0px;");

        // absoluteLayout_5
        absoluteLayout_5 = buildAbsoluteLayout_5();
        mainLayout.addComponent(absoluteLayout_5, "top:280.0px;left:250.0px;");

        // absoluteLayout_18
        absoluteLayout_18 = buildAbsoluteLayout_18();
        mainLayout.addComponent(absoluteLayout_18, "top:80.0px;left:250.0px;");

        return mainLayout;
    }

    @AutoGenerated
    private AbsoluteLayout buildAbsoluteLayout_2() {
        // common part: create layout
        absoluteLayout_2 = new AbsoluteLayout();
        absoluteLayout_2.setImmediate(false);
        absoluteLayout_2.setWidth("100.0%");
        absoluteLayout_2.setHeight("46px");

        // textField_1
        textField_1 = new TextField();
        textField_1.setImmediate(false);
        textField_1.setWidth("-1px");
        textField_1.setHeight("30px");
        textField_1.setInputPrompt("Action");
        absoluteLayout_2.addComponent(textField_1, "top:0.0px;left:3.0px;");

        // textField_18
        textField_18 = new TextField();
        textField_18.setImmediate(false);
        textField_18.setWidth("110px");
        textField_18.setHeight("-1px");
        absoluteLayout_2.addComponent(textField_18, "top:0.0px;left:360.0px;");

        // nativeButton_1
        nativeButton_1 = new NativeButton();
        nativeButton_1.setCaption("NativeButton");
        nativeButton_1.setImmediate(true);
        nativeButton_1.setWidth("70px");
        nativeButton_1.setHeight("-1px");
        absoluteLayout_2
                .addComponent(nativeButton_1, "top:0.0px;left:470.0px;");

        return absoluteLayout_2;
    }

    @AutoGenerated
    private AbsoluteLayout buildAbsoluteLayout_3() {
        // common part: create layout
        absoluteLayout_3 = new AbsoluteLayout();
        absoluteLayout_3.setImmediate(false);
        absoluteLayout_3.setWidth("200px");
        absoluteLayout_3.setHeight("330px");

        // gridLayout_4
        gridLayout_4 = new Grid();
        gridLayout_4.setImmediate(false);
        gridLayout_4.setWidth("200px");
        gridLayout_4.setHeight("280px");

        absoluteLayout_3.addComponent(gridLayout_4, "top:0.0px;left:0.0px;");

        // button_3

        button_3.setImmediate(true);
        button_3.setWidth("-1px");
        button_3.setHeight("26px");
        absoluteLayout_3.addComponent(button_3, "bottom:0.0px;left:120.0px;");

        return absoluteLayout_3;
    }

    @AutoGenerated
    private AbsoluteLayout buildAbsoluteLayout_5() {
        // common part: create layout
        absoluteLayout_5 = new AbsoluteLayout();
        absoluteLayout_5.setImmediate(false);
        absoluteLayout_5.setWidth("100.0%");
        absoluteLayout_5.setHeight("130px");

        // gridLayout_5
        gridLayout_5 = new GridLayout();
        gridLayout_5.setImmediate(false);
        gridLayout_5.setWidth("330px");
        gridLayout_5.setHeight("110px");
        gridLayout_5.setMargin(false);
        absoluteLayout_5.addComponent(gridLayout_5, "top:0.0px;left:0.0px;");

        // button_1
        button_1 = new Button();
        button_1.setCaption("New bid");
        button_1.setImmediate(true);
        button_1.setWidth("100.0%");
        button_1.setHeight("-1px");
        absoluteLayout_5.addComponent(button_1,
                "top:124.0px;right:16.0px;left:240.0px;");

        return absoluteLayout_5;
    }

    @AutoGenerated
    private AbsoluteLayout buildAbsoluteLayout_18() {
        // common part: create layout
        absoluteLayout_18 = new AbsoluteLayout();
        absoluteLayout_18.setImmediate(false);
        absoluteLayout_18.setWidth("330px");
        absoluteLayout_18.setHeight("180px");

        // gridLayout_3
        gridLayout_3 = new GridLayout();
        gridLayout_3.setImmediate(false);
        gridLayout_3.setWidth("100.0%");
        gridLayout_3.setHeight("100.0%");
        gridLayout_3.setMargin(false);
        gridLayout_3.setRows(8);
        absoluteLayout_18.addComponent(gridLayout_3,
                "top:0.0px;right:100.0px;left:110.0px;");

        // textField_2
        textField_2 = new TextField();
        textField_2.setImmediate(false);
        textField_2.setWidth("110px");
        textField_2.setHeight("-1px");
        absoluteLayout_18.addComponent(textField_2, "top:0.0px;right:220.0px;");

        // absoluteLayout_4
        absoluteLayout_4 = buildAbsoluteLayout_4();
        absoluteLayout_18.addComponent(absoluteLayout_4);

        return absoluteLayout_18;
    }

    @AutoGenerated
    private AbsoluteLayout buildAbsoluteLayout_4() {
        // common part: create layout
        absoluteLayout_4 = new AbsoluteLayout();
        absoluteLayout_4.setImmediate(false);
        absoluteLayout_4.setWidth("330px");
        absoluteLayout_4.setHeight("180px");

        // gridLayout_2
        gridLayout_2 = new GridLayout();
        gridLayout_2.setImmediate(false);
        gridLayout_2.setWidth("100.0%");
        gridLayout_2.setHeight("100.0%");
        gridLayout_2.setMargin(false);
        gridLayout_2.setRows(8);
        absoluteLayout_4.addComponent(gridLayout_2,
                "top:0.0px;right:100.0px;left:110.0px;");

        // button_5
        button_5 = new Button();
        button_5.setCaption("Cancel trades");
        button_5.setImmediate(true);
        button_5.setWidth("100.0%");
        button_5.setHeight("-1px");
        absoluteLayout_4.addComponent(button_5,
                "top:154.0px;right:0.0px;left:230.0px;");

        // textField_4
        textField_4 = new TextField();
        textField_4.setImmediate(false);
        textField_4.setWidth("110px");
        textField_4.setHeight("-1px");
        absoluteLayout_4.addComponent(textField_4, "top:0.0px;right:220.0px;");

        // textField_3
        textField_3 = new TextField();
        textField_3.setImmediate(false);
        textField_3.setWidth("110px");
        textField_3.setHeight("-1px");
        absoluteLayout_4.addComponent(textField_3, "top:24.0px;left:0.0px;");

        // textField_12
        textField_12 = new TextField();
        textField_12.setImmediate(false);
        textField_12.setWidth("110px");
        textField_12.setHeight("-1px");
        absoluteLayout_4.addComponent(textField_12, "top:69.0px;left:0.0px;");

        // textField_13
        textField_13 = new TextField();
        textField_13.setImmediate(false);
        textField_13.setWidth("110px");
        textField_13.setHeight("-1px");
        absoluteLayout_4.addComponent(textField_13, "top:48.0px;left:0.0px;");

        // textField_14
        textField_14 = new TextField();
        textField_14.setImmediate(false);
        textField_14.setWidth("110px");
        textField_14.setHeight("-1px");
        absoluteLayout_4.addComponent(textField_14, "top:156.0px;left:0.0px;");

        // textField_15
        textField_15 = new TextField();
        textField_15.setImmediate(false);
        textField_15.setWidth("110px");
        textField_15.setHeight("-1px");
        absoluteLayout_4.addComponent(textField_15, "top:132.0px;left:0.0px;");

        // textField_16
        textField_16 = new TextField();
        textField_16.setImmediate(false);
        textField_16.setWidth("110px");
        textField_16.setHeight("-1px");
        absoluteLayout_4.addComponent(textField_16, "top:114.0px;left:0.0px;");

        // textField_17
        textField_17 = new TextField();
        textField_17.setImmediate(false);
        textField_17.setWidth("110px");
        textField_17.setHeight("-1px");
        absoluteLayout_4.addComponent(textField_17, "top:93.0px;left:0.0px;");

        return absoluteLayout_4;
    }

    void refreshContacts()throws Exception {
        refreshContacts(filter.getValue());
    }

    private void refreshContacts(String stringFilter)throws Exception {
       gridLayout_4.setContainerDataSource(new BeanItemContainer<Lot>(
                Lot.class, service.getAllLots()));
        contactForm.setVisible(false);
    }


    @WebServlet(urlPatterns = "/*")
    @VaadinServletConfiguration(ui = AddressbookUI.class, productionMode = false)
    public static class MyUIServlet extends VaadinServlet {
    }

}
